### ISSUE TITLE
Custom folder called "drivers" not scanned or added to STM32Make.make

### ISSUE THREAD

**Issue by KlaasHofmanVH** [bmd-studio/stm32-for-vscode#118]
Hi,
First of all, thanks for this great plugin!

I happen to notice that sources under the directory called "drivers" are not included in the makefile. 
My sandbox looks like this:

```

├── application_xxxx
│   ├── application : **OK sources are added **
│   ├── drivers ** FAIL: sources are missing **
├── build
├── Core
│   ├── Inc
│   ├── Src
│   └── Startup
├── Drivers
│   ├── CMSIS
│   │   ├── Device
│   │   │   └── ST
│   │   │       └── STM32L4xx
│   │   │           ├── Include
│   │   │           └── Source
│   │   │               └── Templates
│   │   └── Include
│   └── STM32L4xx_HAL_Driver
│       ├── Inc
│       │   └── Legacy
│       └── Src
```

Could it be the plugin is confused by the name "drivers" which is the same as STM's HAL call ed "Drivers" ?

**Comment by jortbmd** [comment]
Hi! Thanks for opening up an issue. Could you perhaps share your STM32-for-VSCode.config.yaml? It should not automatically exclude the driver folder in your aplication_xxxx. Make sure that the globs/source file inclusion in includeDirectories and sourceFiles are correct. 

e.g.: 

```yaml


# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories:
 - Core/Src/**
 - Core/Inc/**
 - application_xxxx/**

sourceFiles:
 - Core/Src/**
 - Core/Inc/**
 - application_xxxx/**
```
