### ISSUE TITLE
MAKEFILE variables

### ISSUE THREAD

**Issue by davidstonely** [bmd-studio/stm32-for-vscode#129]
Hello, very nice extension!!!

I am interested in getting git hash variable defined in my builds as described here

[https://stackoverflow.com/questions/1704907/how-can-i-get-my-c-code-to-automatically-print-out-its-git-version-hash](https://stackoverflow.com/questions/1704907/how-can-i-get-my-c-code-to-automatically-print-out-its-git-version-hash))

I couldn't figure out how to edit the STM32-for-VSCode.config.yaml file so that the GIT_VERSION variable is defined in the makefile. I was able to get it to work correctly if I directly edit the makefile, but it gets overwritten easily that way.

**Comment by jortbmd** [comment]
Thank you!
This would be nice. I do not have a nice wat as of yet to include it. You could potentially create a header file with the define in it. Using an additional make rule and create a new header file with the definition. I would recommend a header file because if you use a -D flag it will recompile your entire project each time that flag changes.

For example if you would add this to you STM32-for-VSCode.config.yaml:
```yaml
customMakefileRules:
- command: gitversion
  rule: $(shell git describe --abbrev=4 --dirty --always --tags | sed 's/.*/#pragma once \n#define \"&\"/' > Core/Inc/git_version.h)
```
you can run:  ``make -f STM32Make.make gitversion`` to create a git_version.h file in Core/Inc
You can also add this to the tasks.json in vscode and have the Build STM task depend on it, so it will be re-generated each time you run build.
